/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package patibayanngbahay;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.*;

/**
 *
 * @author micko
 */
public class HomePage extends javax.swing.JFrame {
    private How howPage;
    private Start startPage;

  public HomePage() {
    initComponents();
    setTitle("Home ");
    setSize(1920, 1080);
    setExtendedState(JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setLayout(null); // Allow absolute positioning
    // Enable button sounds globally
      // Enable sound for all buttons in this frame
     // 🎵 Apply click sound to all buttons automatically!
 
           // 🔥 Add click sound to all buttons
    addClickSoundToButtons();
    Music.playMusic("/patibayanngbahay/sounds/Wii_Music.wav");
    setVisible(true);
    
    howPage = new How();
    howPage.setVisible(false);
    
    startPage = new Start();
    startPage.setVisible(false);
    
    
}
private void addClickSoundToButtons() {
    JButton[] buttons = {setting, HOW, START, EXIT};
    for (JButton button : buttons) {
        button.addActionListener(e -> Music.playClickSound());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setting = new javax.swing.JButton();
        HOW = new javax.swing.JButton();
        START = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Homepage");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setting.setBackground(new java.awt.Color(204, 204, 204));
        setting.setFont(new java.awt.Font("Papyrus", 1, 100)); // NOI18N
        setting.setText("=");
        setting.setToolTipText("Game Setting");
        setting.setAlignmentY(0.0F);
        setting.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 3), // Shadow border
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) // Padding
        ));
        setting.setDefaultCapable(false);
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });
        getContentPane().add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 80, 60));

        HOW.setBackground(new java.awt.Color(204, 204, 204));
        HOW.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        HOW.setText("HOW To PLAY?");
        HOW.setToolTipText("Instructions");
        HOW.setAlignmentY(0.0F);
        HOW.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 3), // Shadow border
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) // Padding
        ));
        HOW.setDefaultCapable(false);
        HOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOWActionPerformed(evt);
            }
        });
        getContentPane().add(HOW, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 930, 400, 60));

        START.setBackground(new java.awt.Color(204, 204, 204));
        START.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        START.setText("START");
        START.setToolTipText("Start Game");
        START.setAlignmentY(0.0F);
        START.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 3), // Shadow border
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) // Padding
        ));
        START.setDefaultCapable(false);
        START.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STARTActionPerformed(evt);
            }
        });
        getContentPane().add(START, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 780, 400, 60));

        EXIT.setBackground(new java.awt.Color(204, 204, 204));
        EXIT.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.setToolTipText("Exit Game");
        EXIT.setAlignmentY(0.0F);
        EXIT.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 3), // Shadow border
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) // Padding
        ));
        EXIT.setDefaultCapable(false);
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 860, 400, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patibayanngbahay/pic/bg.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOWActionPerformed
     
   
     howPage.setVisible(true);  
     howPage.toFront();          // Bring it to the front
     howPage.requestFocus();     // Ensure it gets focus

        dispose(); // Close the old frame after ensuring the new one is visible

   
    }//GEN-LAST:event_HOWActionPerformed

    private void STARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STARTActionPerformed
       
      
         startPage.setVisible(true);  
     startPage.toFront();          // Bring it to the front
    startPage.requestFocus();    
        dispose(); // Close the old frame after ensuring the new one is visible
  
    }//GEN-LAST:event_STARTActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
    
		
				  JLabel meme = new JLabel();
            
            // Load image correctly as a resource
            ImageIcon icon = new ImageIcon(getClass().getResource("/patibayanngbahay/pic/leave.gif")); 
            
            meme.setIcon(icon);
                 
                 String []options = {"Yes", "No"};
				int x = JOptionPane.showOptionDialog(null, meme, "Thank you and Good Bye!", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
				if (x == 0) {
					System.exit(0);
    				}else {
                                 new HomePage();
                                 dispose(); 
   
 		
				}
			
                // TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        // TODO add your handling code here:
                      new setting().setVisible(true);
    }//GEN-LAST:event_settingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton HOW;
    private javax.swing.JButton START;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton setting;
    // End of variables declaration//GEN-END:variables


}
