/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package patibayanngbahay;


import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author micko
 */
public class How extends javax.swing.JFrame {

     private How_1 how_1Page;
     private HomePage homePage;
     
     public How() {
    initComponents();
    setTitle("How to Play the Game");
    setExtendedState(JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);
    
    setVisible(true);
  addClickSoundToButtons();
   
        
    }

    private void addClickSoundToButtons() {
    JButton[] buttons = { next,back};
    for (JButton button : buttons) {
        button.addActionListener(e -> Music.playClickSound());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        how_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 204, 51));
        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel2.setText("Destroy your opponent’s house while protecting your own. The last house standing wins!");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 980, 30));

        jLabel5.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel5.setText("1.Players decide who will be Player 1 and Player 2.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 980, 30));

        jLabel6.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel6.setText("2. Player 1 chooses a house first and reinforces it.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 980, 30));

        jLabel7.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel7.setText("3. Player 2 then selects a house and reinforces it.  ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 980, 30));

        jLabel8.setBackground(new java.awt.Color(255, 204, 51));
        jLabel8.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel8.setText("Game Setup:  ");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 170, 30));

        jLabel9.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel9.setText("4.The game begins, and turns alternate between players.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, 980, 30));

        next.setBackground(new java.awt.Color(204, 204, 204));
        next.setFont(new java.awt.Font("Papyrus", 1, 120)); // NOI18N
        next.setText(">");
        next.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 3), // Shadow border
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) // Padding
        ));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 450, 100, 100));

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        back.setText("BACK");
        back.setToolTipText("Back To Menu");
        back.setAlignmentY(0.0F);
        back.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 3), // Shadow border
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) // Padding
        ));
        back.setDefaultCapable(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 940, 270, 60));

        how_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patibayanngbahay/pic/how_bg.png"))); // NOI18N
        how_bg.setText("jLabel1");
        how_bg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(how_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
                                   
        if (how_1Page == null) {
            how_1Page = new How_1();
        }
        how_1Page.setVisible(true);
        how_1Page.toFront();
        how_1Page.requestFocus();
        setVisible(false);
					
        
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
     
       if (homePage == null) {
            homePage = new HomePage();
        }
        homePage.setVisible(true);
        homePage.toFront();
        homePage.requestFocus();
        setVisible(false);
       
       // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(How.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(How.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(How.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(How.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new How().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton back;
    javax.swing.JLabel how_bg;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
