/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package patibayanngbahay;


import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author micko
 */
public class How_1 extends javax.swing.JFrame {
     private How howPage;
     private How_2 how_2Page;
     private HomePage homePage;
     
     public How_1() {
    initComponents();
    setTitle("How to Play the Game");
     setExtendedState(JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

  addClickSoundToButtons();
   
        
    }

    private void addClickSoundToButtons() {
    JButton[] buttons = { next,back,next1};
    for (JButton button : buttons) {
        button.addActionListener(e -> Music.playClickSound());
    }
}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        next1 = new javax.swing.JButton();
        how_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel3.setText("Collected items activate on the next turn.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 1080, 30));

        jLabel4.setBackground(new java.awt.Color(255, 204, 51));
        jLabel4.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel4.setText("Gameplay:  ");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 140, 30));

        jLabel10.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel10.setText("Randomized Throw: Each turn, the game randomly selects Paper, Rock, or Bomb as the \"pambato\".");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 1080, 30));

        jLabel11.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel11.setText("Power-Ups reinforce or repair your house.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 1080, 30));

        jLabel12.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel12.setText("Aim & Launch: Adjust angle & power, then \"BATO!\".");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 1080, 30));

        jLabel13.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel13.setText("Sabotage Items weaken your opponent’s house or disrupt their next throw.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 1080, 30));

        jLabel14.setBackground(new java.awt.Color(255, 204, 51));
        jLabel14.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel14.setText("Winning Condition:");
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 700, 230, 30));

        jLabel15.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel15.setText("The game ends when one house is completely destroyed. The remaining player wins!");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 750, 1080, 30));

        jLabel16.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel16.setText("Physics Apply: \"Pambato\" follow a trajectory and impact the opponent’s house lessen the houselife.");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 1080, 30));

        jLabel17.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel17.setText("Floating Power-Ups & Sabotage Items:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 1080, 30));

        next.setBackground(new java.awt.Color(204, 204, 204));
        next.setFont(new java.awt.Font("Papyrus", 1, 120)); // NOI18N
        next.setText("<");
        next.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 3), // Shadow border
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) // Padding
        ));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 100, 100));

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        back.setText("BACK");
        back.setToolTipText("Back To Menu");
        back.setAlignmentY(0.0F);
        back.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 3), // Shadow border
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) // Padding
        ));
        back.setDefaultCapable(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 940, 270, 60));

        next1.setBackground(new java.awt.Color(204, 204, 204));
        next1.setFont(new java.awt.Font("Papyrus", 1, 120)); // NOI18N
        next1.setText(">");
        next1.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 3), // Shadow border
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) // Padding
        ));
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });
        getContentPane().add(next1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 450, 100, 100));

        how_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patibayanngbahay/pic/how_bg.png"))); // NOI18N
        how_bg.setText("jLabel1");
        how_bg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(how_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
       if (howPage == null) howPage = new How();
        howPage.setVisible(true);
        this.setVisible(false);
      

    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      
      if (homePage == null) homePage = new HomePage();
        homePage.setVisible(true);
        this.setVisible(false);
    
      
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed
        // TODO add your handling code here:
       
        if (how_2Page == null) how_2Page = new How_2();
        how_2Page.setVisible(true);
        this.setVisible(false);
    
   
         
    }//GEN-LAST:event_next1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(How.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(How.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(How.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(How.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>c

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new How_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton back;
    javax.swing.JLabel how_bg;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel14;
    javax.swing.JLabel jLabel15;
    javax.swing.JLabel jLabel16;
    javax.swing.JLabel jLabel17;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JButton next;
    javax.swing.JButton next1;
    // End of variables declaration//GEN-END:variables
}
