/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package patibayanngbahay;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicSliderUI;
import java.util.prefs.Preferences;
/**
 *
 * @author micko
 */
public class setting extends javax.swing.JFrame {

    Preferences prefs = Preferences.userRoot().node(this.getClass().getName());
    public setting() {
        initComponents();
     setLocationRelativeTo(null);
 
       try {
        javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
    } catch (Exception e) {
        e.printStackTrace();
    }
       addClickSoundToButtons();
    // Apply Custom Styling
     customizeSlider();
     
     int savedMusic = prefs.getInt("musicVolume",50);
      int savedSound = prefs.getInt("soundVolume",50);
     
      MusicSlider.setValue(savedMusic);
      SoundSlider.setValue(savedSound);
    }

    private void addClickSoundToButtons() {
    JButton[] buttons = { About};
    for (JButton button : buttons) {
        button.addActionListener(e -> Music.playClickSound());
    }
}/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MusicSlider = new javax.swing.JSlider();
        About = new javax.swing.JButton();
        SoundSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(935, 535));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patibayanngbahay/pic/musicon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patibayanngbahay/pic/von.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        MusicSlider.setForeground(new java.awt.Color(51, 51, 51));
        MusicSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MusicSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MusicSliderStateChanged(evt);
            }
        });
        jPanel1.add(MusicSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 420, 40));

        About.setBackground(new java.awt.Color(204, 204, 204));
        About.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        About.setText("ABOUT");
        About.setToolTipText("About");
        About.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 3), // Shadow border
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5) // Padding
        ));
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        jPanel1.add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        SoundSlider.setForeground(new java.awt.Color(51, 51, 51));
        SoundSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SoundSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SoundSliderStateChanged(evt);
            }
        });
        jPanel1.add(SoundSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 410, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patibayanngbahay/pic/bg2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 928, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SoundSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SoundSliderStateChanged
    int value = SoundSlider.getValue();
    float volume = SoundSlider.getValue() / 100f; // Convert from 0-100 to 0.0-1.0
    Music.setClickVolume(volume);
    prefs.putInt("soundVolume", value);
    updateVolumeIcon();
    }//GEN-LAST:event_SoundSliderStateChanged

    private void MusicSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MusicSliderStateChanged
        int value = MusicSlider.getValue();
        float volume = value / 100f;
        Music.setMusicVolume(volume);
        prefs.putInt("musicVolume", value);  // Save value
        updateMusicIcon();
    }//GEN-LAST:event_MusicSliderStateChanged

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    /**
     * @param args the command line arguments
  
 */
private void customizeSlider() {
   MusicSlider.setUI(new PencilVolumeSliderUI(MusicSlider));
    MusicSlider.setOpaque(false);
    MusicSlider.setPaintTicks(false);
    MusicSlider.setPaintLabels(false);
      SoundSlider.setUI(new PencilVolumeSliderUI(SoundSlider));
    SoundSlider.setOpaque(false);
    SoundSlider.setPaintTicks(false);
    SoundSlider.setPaintLabels(false);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setting().setVisible(true);
            }
        });
    }
    private void updateVolumeIcon() {
             if (SoundSlider.getValue() == 0) {
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patibayanngbahay/pic/voff.png"))); //Muted
        }else{
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patibayanngbahay/pic/von.png"))); // Volume icon
        }
    }
    
        private void updateMusicIcon() {
             if (MusicSlider.getValue() == 0) {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patibayanngbahay/pic/musicoff.png"))); //Muted
        }else{
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patibayanngbahay/pic/musicon.png"))); // music icon
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton About;
    javax.swing.JSlider MusicSlider;
    javax.swing.JSlider SoundSlider;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}



// Custom method to style the slider
